# Network user defined
# Tire d'ici : https://earthly.dev/blog/docker-networking/

version: '3.7'
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    # Following each service, I added the network key to specify that these services should connect to mynetwork.
    networks:
      - mynetwork
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    # Following each service, I added the network key to specify that these services should connect to mynetwork.
    networks:
      - mynetwork
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
volumes:
  db_data:

# I’ve defined a user-defined network under the top-level networks section
# and called the network mynetwork. It’s a bridge type, meaning it’s a network on the host machine
# separated from the rest of the host network stack.
networks:
  mynetwork:
